---
- name: Deploy xray config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ xray_config_dir }}/config.json"
    owner: root
    group: root
    mode: '0640'
  notify: restart xray

- name: Verify config syntax
  ansible.builtin.command: >
    {{ xray_install_dir }}/xray run -test
    -config {{ xray_config_dir }}/config.json
  changed_when: false
  register: config_test

- name: Show config test result
  ansible.builtin.debug:
    msg: "{{ config_test.stdout_lines }}"
